create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer jsonb not null,
  order_type text not null default 'table' check (order_type in ('delivery', 'pickup', 'table')),
  table_number text,
  delivery_address text default '',
  items jsonb not null,
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  total numeric(10, 2) not null check (total >= 0),
  payment_method text not null default 'in-store',
  order_status text not null default 'Pending' check (order_status in ('Pending', 'Confirmed', 'Preparing', 'Ready', 'Completed', 'Cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (order_status);

alter table public.orders enable row level security;

revoke all on public.orders from anon, authenticated;
grant all on public.orders to service_role;
